### ISSUE TITLE
faulty resolution.

### ISSUE THREAD

**Issue by user45786** [SafwanLjd/EgyBestTeleBot#4] opened 2022-04-30 20:17 UTC
hey i recently noticed that some movies/shows has a faulty resolution like in the picture (240  240 ....)
and when downloading from a link .. it's actually not the same as it says... there is miscommunication somewhere.

![Screenshot_2022-04-30-23-14-32-925_ir ilmili telegraph](https://user-images.githubusercontent.com/104211724/166121280-8fbc16b8-e2ee-473b-887f-b36ab1c30956.jpg)

**Comment by SafwanLjd** [comment] 2022-12-29 23:10
This is an issue with the original (PyEgyBest)[https://github.com/SafwanLjd/PyEgyBest]  library, which is caused by the way it parses the resolution, you have to understand that these resolution values come from the width of the picture of the video file, and with new cinematic media that uses weird aspect ratios, the width of the pictures is rarely a neat round number (i.e. 480, 720, etc), however these are the values that people are used to (mainly because of YouTube), so it just rounds the number of pixels to the nearest neat number, in the case you show, the width just happened to be closer to 240 than to 360 in the case of the first two available resolutions. Anyway I'm closing this issue because, as I said, it has nothing to do with the code in this repo, as it is an issue with the library used.

**Closed as completed by SafwanLjd** 2022-12-29 23:10 UTC
